### ISSUE TITLE
Dropped still appears in "Airing Soon"

### ISSUE THREAD

**Issue by ChristopheRoyer21** [axiel7/AniHyou-android#100]
**Describe the bug (required)**
Even if I drop a serie,.it still appears in the "Airing soon" section 

**To Reproduce**
1. Enable "Only in list" for the Airing Soon categorie
2. Set the status of an anime that is airing to "Dropped"
3. We can see that the serie doesn't disappear from the "Airing soon" section, despite enabling "Only in list"

**Expected behavior**
To be fair, it might not be a bug since it's still "in the list", but it should be excluded since it is dropped

**Enviroment (required)**
 - Device model:  Pixel 5

**Comment by axiel7** [comment]
It's not a bug, it's a feature ;)

Joking, I'll have to manually filter the dropped (and paused?) entries

**Comment by ChristopheRoyer21** [comment]
Yeah indeed, I feel like paused anime should be filtered out as well. Or maybe giving an additionnal option in the setting "Exclude Dropped and Paused"?

**Comment by ChristopheRoyer21** [comment]
Thank you!!
