### ISSUE TITLE
Next Season on Home shows old shows (Winter 2023)

### ISSUE THREAD

**Issue by jack-mil** [axiel7/AniHyou-android#11]
**Describe the bug (required)**
The Next Season section of the home screen lists shows that aired in Winter 2023 (a previous season). 

**To Reproduce**
1. Home screen, Next Season section

**Expected behavior**
I think "Next Season" should be either Winter 2024 or Fall 2023, as of 9/21/23 (depending on whether Summer 2023 is considered over yet). Definitely not already completed shows

**Screenshots**
![Screenshot_20230921-124226.jpg](https://github.com/axiel7/AniHyou-android/assets/62065280/2f99378e-0395-432f-9f6e-7ff483dff270)

**Enviroment (required)**
 - Device model: Tested on several (OnePlus 6, Galaxy Tab S5e
 - Android version: 11 and 13
 - App version: 1.1.8 ( was also present on previous version)

**Additional context**
I assume this is unintentional? but it seems odd that no one else has noticed it yet, so maybe I am mistaken and this isn't a bug.

**Comment by axiel7** [comment]
Indeed I fixed this on the iOS version but forgot to do it on Android. Thanks for reporting

**Comment by axiel7** [comment]
Fixed [1.2.1](https://github.com/axiel7/AniHyou-android/releases/tag/1.2.1)
