### ISSUE TITLE
Voice Actors name in the Characters/Staff section

### ISSUE THREAD

**Issue by ChristopheRoyer21** [axiel7/AniHyou-android#118]
**Request (required)**
I wa surprised it wasn't there (Or I just didn't find it), but it would be nice to have the name of the voice actor of the characters when we go in the staff section. This is actually one of the main reason I go to anilist and it would be nice to have it in your app.

Either in the list of character or when we click on the character. But the former would better since we can see them all at a glance. I personally think that is more important than know than Main vs Supporting

**Additional context (optinal)**
Thank you!

**Examples (optional)**
It exists on the official Anilist and MyAnimeList websites

**Comment by axiel7** [comment]
Yes I plan to rework the anime characters view so it shows the voice actors. I've done this in the iOS version
