### ISSUE TITLE
Extensión

### ISSUE THREAD

**Issue by Alex178190282** [axiel7/AniHyou-android#120]
**Request (required)**
Describe the feature you want to be implemented.

The app is great, my favorite interface in all these years of trying apps of this type, but after so much time I have a suggestion that I hope can be fulfilled. You can add the Aniyomi/mihon extensions repository to the app. I'm sure that would help extend the app. the app much more and would be the favorite of many

**Additional context (optinal)**
Add any other context or app screenshots about the feature request here.

I already said it in the first part

**Examples (optional)**
Show here examples of the feature if exists in other app.

Extensions
Bring your own content from a variety of sources.

**Comment by axiel7** [comment]
Do you mean watching anime in the app? AniHyou main purpose is to be an AniList client for managing anime/manga list. If you want to watch anime use another app developed for that purpose. Thank you anyway

**Comment by Alex178190282** [comment]
> Do you mean watching anime in the app? AniHyou main purpose is to be an AniList client for managing anime/manga list. If you want to watch anime use another app developed for that purpose. Thank you anyway

Well, sorry and sorry for the inconvenience.
