### ISSUE TITLE
Not recieving airing anime push notifications

### ISSUE THREAD

**Issue by pagusupu** [axiel7/AniHyou-android#137]
**Describe the bug**
Not receiving airing anime push notifications. 

**Environment**
 - Device model: Nothing Phone (1)
 - Android version:  14
 - App version:  1.2.5

**Additional Context**
I haven't received *any* notifications from the app in quite some time but I'm unsure as to whether that's because i just haven't actually gotten any notifications other than airing anime or not.
Notifications are also enabled on my anilist account.

**Screenshots**
![Screenshot_20240517-105046](https://github.com/axiel7/AniHyou-android/assets/114620038/f3e51a10-6ab7-4e60-bed2-83e42cbad5d9)
![Screenshot_20240517-105100](https://github.com/axiel7/AniHyou-android/assets/114620038/98acc022-3d7b-4548-9cb8-8fdd8d98ca6c)

**Comment by axiel7** [comment]
It's a known issue, this is currently fixed in the 1.2.6 beta

**Comment by pagusupu** [comment]
Is this 1.2.5-1 or is there no release for it yet?

**Comment by axiel7** [comment]
It's not in the stable version yet, I was busy.

You can install the beta from Play Store or from Discord

**Comment by pagusupu** [comment]
Thanks!
