### ISSUE TITLE
Volume count in manga stats page get reset to 1

### ISSUE THREAD

**Issue by ynhame** [axiel7/AniHyou-android#144]
**Describe the bug (required)**

when I go to profile, in the manga overview section
the volumes read count is stuck at one.

if I go to the anilist site it displays 2513 volumes read.

the chapters read is displayed correctly

**To Reproduce**
1. Go to the profile tab
2. go to the status section (the bar plot icons)
3. select overview (the default)
4. select manga (the deafult is anime)
5. see the volumes read count

**Expected behavior**
the correct number to be shown

**Screenshots**

![image](https://github.com/axiel7/AniHyou-android/assets/107622956/ce00e898-83b1-4343-af1c-cbd30a8f833a)

![Screenshot_20240603-101810_AniHyou](https://github.com/axiel7/AniHyou-android/assets/107622956/5fd7a78c-7fe1-4c5f-9fd8-1a416ed5708b)

**Enviroment (required)**
 - Device model: poco x3 NFC
 - Android version: 14
 - App version: 1.3.0

**Additional context (optional)**

**Comment by axiel7** [comment]
Oops, nice find. This is happening because it's converting 2513 to days. Next update will fix it :)

**Comment by axiel7** [comment]
Fixed in beta 1.3.2
