### ISSUE TITLE
'Black theme variant' overlaps light theme

### ISSUE THREAD

**Issue by akyraisconfused** [axiel7/AniHyou-android#145]
**Describe the bug (required)**
When switching to light theme with 'Black theme variant' enabled, some elements switch to their light theme colors but the background stays black.

**To Reproduce**
1. Go to AniHyou's settings
2. Enable 'Black theme variant'
3. Switch to light theme

Steps 2 and 3 are interchangeable.

**Expected behavior**
Background turning light.

**Screenshots**
![Screenshot_20240603_181220_AniHyou](https://github.com/axiel7/AniHyou-android/assets/139814707/62b6d22a-5ebf-42f8-8cf9-6d92fc0f8c64)

**Enviroment (required)**
 - Device model: Samsung Galaxy S22 (SM-S901E/DS)
 - Android version: Android 14, April Security Patch
 - App version: 1.3.1

**Comment by axiel7** [comment]
Mmm I can't reproduce this on my device. If you restart the app it stays the same?

**Comment by akyraisconfused** [comment]
yup, i cleared data in an attempt to fix a bug with lists (which worked) but this still happens. maybe i'll try reinstalling.

**Comment by axiel7** [comment]
Nah this is problably a bug with OneUI, I'll block that option in light mode

**Comment by akyraisconfused** [comment]
yeah gave it a try on my Tab A 2019 and the same result, definitely a Samsung issue like the Material You one.

**Comment by axiel7** [comment]
Beta 1.3.2 should fix this

**Comment by akyraisconfused** [comment]
strangely enough this still occurs for me on 1.3.2
