### ISSUE TITLE
Refresh activity comments

### ISSUE THREAD

**Issue by akyraisconfused** [axiel7/AniHyou-android#146]
**Request (required)**
Currently, activity comments no longer refresh without restarting the app once they're loaded. This means any new comments to that activity are not viewable, and your likes to existing comments are not visible if you close and open the comment section.

Reloading/refreshing an activity's comments whenever that section is opened or giving a manual refresh option would fix this.

**Comment by axiel7** [comment]
True they're cached. I'll add a swipe to refresh
