### ISSUE TITLE
Show the actual dates in the Anime and Manga list

### ISSUE THREAD

**Issue by mag0bei** [axiel7/AniHyou-android#147]
**Request (required)**
Describe the feature you want to be implemented.
In the anime and manga list tabs, we can sort these lists by update date, added date and start date. I believe these are user related. Is there a way to show these different dates?
**Additional context (optional)**
Add any other context or app screenshots about the feature request here.
Alternatively can we add them dynamically in the status distribution tab of each anime and manga ?
**Examples (optional)**
Show here examples of the feature if exists in other app.

**Comment by axiel7** [comment]
Update date and added date aren't even that important to show it in the list. Start date and end date can be seen in the edit sheet (long press).

I don't think I'll do this
