### ISSUE TITLE
Dynamic theme doesn't work in 1.3.3

### ISSUE THREAD

**Issue by HotarunIchijou** [axiel7/AniHyou-android#152]
#  **Describe the bug**
For some reason after logging in to the account the default theme is applied instead of system one 

# **Screenshots**
### How it should look like (before logging in):
![](https://github.com/axiel7/AniHyou-android/assets/113282550/c08fdcf3-ad44-4d2d-bd55-f57310477ea2)

### How it actually looks:
![](https://github.com/axiel7/AniHyou-android/assets/113282550/e8c07296-d190-414a-98f0-e7bf39dcbf71)

# **Enviroment**
 - **App version: 1.3.3**

# **Additional context**
Bro skill issue 💀💀💀

**Comment by axiel7** [comment]
Does the app color changes when viewing another user profile?

> Bro skill issue 💀💀💀

Fix it yourself then 💀

**Comment by HotarunIchijou** [comment]
> Does the app color changes when viewing another user profile?

Yes, it does, but after preventing back gesture it resets

https://github.com/axiel7/AniHyou-android/assets/113282550/540cc6d5-a246-4571-83e0-73287edd7511



> > Bro skill issue 💀💀💀
> 
> Fix it yourself then 💀

Sorry

**Comment by axiel7** [comment]
Okay, and if you go to Settings -> Color and set it to Profile. Does the app color also changes?

**Comment by HotarunIchijou** [comment]
No

**Comment by axiel7** [comment]
Okay, try this apk and let me know if it's fixed

https://wormhole.app/PjmOz#Is0gW00DoOA5gJGfoLdDyw

**Comment by HotarunIchijou** [comment]
It keeps resetting after preventing back gesture

https://github.com/axiel7/AniHyou-android/assets/113282550/6552722b-50a0-4e19-a530-bea2dd483ff3

**Comment by HotarunIchijou** [comment]
Also it changes on some pages

https://github.com/axiel7/AniHyou-android/assets/113282550/0ae08b32-655e-4b30-8c0a-1c48ef9b9235

**Comment by axiel7** [comment]
That is the excepted behaviour. When viewing an user profile it uses the user profile color to color the UI, just like AniList website

**Comment by HotarunIchijou** [comment]
But it doesn't make sense. Also, home page sometimes appears in profile based theme as well

**Comment by axiel7** [comment]
1.3.3 (37) should fix this
