### ISSUE TITLE
Also show tracking details in secondary menu

### ISSUE THREAD

**Issue by NeKoOuO** [axiel7/AniHyou-android#157]
**Additional context (optional)**
![Screenshot_2024-06-29-16-42-35-720_com.axiel7.anihyou-edit.jpg](https://github.com/axiel7/AniHyou-android/assets/111511925/e164771c-67b9-430c-bc50-0e9c6b9678f4)

**Examples (optional)**
![Screenshot_2024-06-29-16-42-07-425_com.axiel7.anihyou-edit.jpg](https://github.com/axiel7/AniHyou-android/assets/111511925/718ca851-723b-47a5-81c8-4f99203ae424)

**Comment by NeKoOuO** [comment]
It looks like this space was originally intended for scores, so perhaps placing it in the top left corner would be a good choice.

**Comment by axiel7** [comment]
Yes I wanted to change this but I forgot. This will be the new design:

<img width="291" alt="Screenshot 2024-06-29 at 14 01 34" src="https://github.com/axiel7/AniHyou-android/assets/12379835/25e74659-1cc5-4688-9cbe-376bcfcab7fe">

**Comment by NeKoOuO** [comment]
Thx! That would be nice

**Comment by axiel7** [comment]
Implemented in beta 1.3.4 (76)
