### ISSUE TITLE
Repeating List is empty

### ISSUE THREAD

**Issue by Zoniax63** [axiel7/AniHyou-android#166]
**Describe the bug (required)**
If I want to look at the "repeating list" there is nothinh inside it even tho im rewatching some anime. The anime with the status "repeating aren't shown at all"

**To Reproduce**
1. Try to find the anime with the "repeating" status without the search bar in the "all list" or "repeating list"

**Expected behavior**
The anime with the Status "repeating" should be shown

**Screenshots**

**Enviroment (required)**
 - Device model: Samsung ZFlip 5
 - Android version: 14
 - App version: 1.3.3 (75)

**Additional context (optional)**

**Comment by Zoniax63** [comment]
Screenshots:
![Screenshot_20240716_132702_AniHyou.jpg](https://github.com/user-attachments/assets/f4b503ae-dbac-4f29-85e8-7c5b9caeea09)

![Screenshot_20240716_132709_AniHyou.jpg](https://github.com/user-attachments/assets/faec1bbc-e6c5-42e4-aef1-0e81e817bc7e)

![Screenshot_20240716_132522_AniHyou.jpg](https://github.com/user-attachments/assets/1ba2d972-0a46-4906-a168-fb318d85c7e0)

**Comment by axiel7** [comment]
Are you sorting the list by update date?

**Comment by axiel7** [comment]
Fixed in beta 1.3.4 (77)
