### ISSUE TITLE
show reason entry received site data changes

### ISSUE THREAD

**Issue by Aiz0** [axiel7/AniHyou-android#182]
## Request
You can get notifications that a media entry received site data changes.
On the Anilist website you can show the reason for this but I can't find a way to show this on Anihyou.
There should be a way to see the reason the entry received changes from the notificaton.

## Examples
Anilist website
![image](https://github.com/user-attachments/assets/8634edb0-e18e-4568-a774-006bff9df04c)
![image](https://github.com/user-attachments/assets/28e4792c-61c8-4f52-a7b1-24f778dff593)

**Comment by axiel7** [comment]
i forgor

**Comment by axiel7** [comment]
Implemented in latest [beta](https://github.com/axiel7/AniHyou-android/actions/runs/10869132753)
