### ISSUE TITLE
Customizable Default Opening Tab

### ISSUE THREAD

**Issue by fraluc06** [axiel7/AniHyou-android#187]
I propose adding a setting to the app that allows users to choose their preferred starting tab when the app is launched. Currently, the app defaults to the last tab visited before closing.

This would enhance user experience by providing flexibility and catering to individual preferences. For example, users might prefer to start on the "**Explore**" tab to quickly find new anime or on the "**Profile**" tab to manage their things.

**Comment by axiel7** [comment]
Implemented in latest [beta](https://github.com/axiel7/AniHyou-android/actions/runs/10869132753)

**Comment by fraluc06** [comment]
Thank you very much! In the near future, I will switch to IOS, is this function present in the IOS version? If not, can you add it to the todo list?

**Comment by axiel7** [comment]
Yes I'll add it later
