### ISSUE TITLE
Seasonal titles show the wrong year

### ISSUE THREAD

**Issue by Felix248** [axiel7/AniHyou-android#197]
When I click on winter anime in the explore tab it says "Winter 2024" but it shows the winter animes from 2023.
![Screenshot_20240908-214553](https://github.com/user-attachments/assets/c6eb7759-246a-40c3-bb15-e24c456818d1)

**Comment by axiel7** [comment]
AniList bug: https://anilist.co/search/anime?year=2024&season=WINTER
