### ISSUE TITLE
Seasonal browse bug

### ISSUE THREAD

**Issue by Swadhin05** [axiel7/AniHyou-android#2]
**Describe the bug (required)**
Year automatically change to 2023 when browsing an anime in season tab. I can't phrase it well, please read below steps

**To Reproduce**
1. Go to explore tab 
2. Click on any season for example spring 
3. Select another year like 2019
4. Click on any anime to read it's description
5. Press back button and it's back to 2023

**Expected behavior**
It's supposed to stay in 2019 for single back gesture. Current behaviour makes difficult to browse an older season

**Enviroment (required)**
 - Android version: Android 10
 - App version: 1.0.2

**Comment by axiel7** [comment]
Fixed: [SeasonAnimeView: save season state](https://github.com/axiel7/AniHyou-android/commit/498ac2e325790a5d13fafb096db237af5b864ca2)
