### ISSUE TITLE
Can't comment in my activity (Error 400)

### ISSUE THREAD

**Issue by Miraihi** [axiel7/AniHyou-android#203]
**Describe the bug (required)**
Can't write a comment in my activity. Honestly, can't write anything at all, including comments in episode threads.

**To Reproduce**
1. Go to Home
2. Click on Activity
3. Press +
4. Write anything, send.
5. See error "HTTP request failed with status code `400`"

**Expected behavior**
Well, proceeding with a comment or status message 

**Screenshots**
![Screenshot_2024-09-28-14-49-42-827_com axiel7 anihyou-edit](https://github.com/user-attachments/assets/0ddb2180-4927-41b8-b6f3-47919507e243)

**Enviroment (required)**
 - Device model: POCO M5s
 - Android version: 14
 - App version: 1.3.4

**Comment by axiel7** [comment]
Fixed in latest beta build
