### ISSUE TITLE
Add translations for the positions of people in the "Staff"

### ISSUE THREAD

**Issue by hualiong** [axiel7/AniHyou-android#216]
**Request (required)**
I noticed that the positions of people in the Staff have not been translated, could you please add translations for them?

**Additional context (optional)**
![8df0da3b0c3b588e8914ec3da9404387](https://github.com/user-attachments/assets/070c4604-74c2-464b-819e-0440c57ad69f)

**Comment by axiel7** [comment]
They are a lot of strings (~200) but I already planned to do it anyway. I'll try to upload them today

**Comment by hualiong** [comment]
Oh~ I see.

I think this information might be important to some people.

Thanks for your hard work.🙏
