### ISSUE TITLE
Add sort by "end date" option

### ISSUE THREAD

**Issue by BaccanoMob** [axiel7/AniHyou-android#239]
https://anilist.co/search/manga?sort=END_DATE_DESC

I mentioned it in zend10/AL-chan#162 just today. 

This makes recently completed manga viewable in app (according to Anilist that is). It should be doable in search (since its accepts as a query parameter in url) not sure in manga list tab.

**Comment by axiel7** [comment]
I didn't added it at first because I thought nobody would use it :)
