### ISSUE TITLE
Empty text search not possible after searching with text once

### ISSUE THREAD

**Issue by BaccanoMob** [axiel7/AniHyou-android#241]
Similar to #50

You can't search with empty text if you searched with text once.

1. Search something in explore tab (with text search)
2. Wait for results to show up.
3. Clear text and try to search with empty text.

Work around is to restart the app.

**Comment by axiel7** [comment]
I can't reproduce this on 1.3.5. 

> 3. Clear text and try to search with empty text.

What filter are you trying to apply?

**Comment by BaccanoMob** [comment]
https://github.com/user-attachments/assets/b7c3b942-a9c4-4168-afab-b081199221b2

I meant the text field becomes unsearchable with empty text. It still works if I enter another test but I can not search with it being empty.

**Comment by axiel7** [comment]
That happens because you don't have any filter applied. Try the same but first apply at least one filter (e.g. TV Format)

**Comment by BaccanoMob** [comment]
Yea with atleast one filter it works as intended. Without filters it doesn't do anything like in the video.

**Comment by axiel7** [comment]
So that's the intended behavior, the app shouldn't search without  filters and empty text
