### ISSUE TITLE
Explore tab icon as scroll to top action

### ISSUE THREAD

**Issue by BaccanoMob** [axiel7/AniHyou-android#243]
Been using search features for awhile. When I want to change filters after scrolling down a lot, I have to swipe a few times to scroll to top.

It would helpful to have explore tab icon act as scroll to top action button when that tab is active. So I can change the filters quickly.

Or filters should act like sticky header so they are always available when scrolled up. 

Alternatives filters should be in a different screen or like bottom sheet or something similar so it's easier to edit after scrolling through after a while.

**Comment by axiel7** [comment]
I ended up adding a button that shows when you scroll.

![image](https://github.com/user-attachments/assets/59278ec9-b2a8-45b6-a5ac-89c065745594)
