### ISSUE TITLE
Some translation of 'activity' is incorrect

### ISSUE THREAD

**Issue by hualiong** [axiel7/AniHyou-android#245]
**Describe the bug (required)**
Some translation of 'activity' is incorrect. It didn't work.

**To Reproduce**
1. Go to 'activity'

**Expected behavior**
The text is translated correctly.

**Screenshots**
![Screenshot_2024-11-29-13-00-35-412_com axiel7 ani](https://github.com/user-attachments/assets/18ebdef5-5ff0-4931-a701-00e5499e40d1)

**Enviroment (required)**
 - Device model: MI 6
 - Android version: 9
 - App version: 3.5.1 (beta)

**Comment by hualiong** [comment]
Did you forget to add the translation to the Crowdin project?🤔
I didn't find a translation like "Paused watching %s" or "Paused reading %s".

**Comment by axiel7** [comment]
I changed it to use "Paused %s" instead

**Comment by hualiong** [comment]
I have found some more strange texts that have not been translated, like the following two examples:

In AniHyou, it appears as "Rewatched %d of %s" because the word "episode" is missing, so the translation did not match.
![IMG_20241212_133633](https://github.com/user-attachments/assets/36c6541c-1fe3-4b02-86f4-b50480d5af96)

However, on AniList, it only shows as "Rewatched %s".
![image](https://github.com/user-attachments/assets/ff5901a1-cade-4b87-b417-0ce65170e1d3)
