### ISSUE TITLE
Sorting by Title/Popularity

### ISSUE THREAD

**Issue by Swadhin05** [axiel7/AniHyou-android#3]
**Request (required)**
I personally prefer anime/manga list in alphabetical order. Pls add it

**Examples**

![IMG_20230602_114554](https://github.com/axiel7/AniHyou-android/assets/105983671/184a1efe-162e-4919-83ec-b4adcd7e1c06)

**Comment by axiel7** [comment]
There's currently a bug in the AniList API that returns wrong data when sorting by title. I plan to add this option but I'll need some time to think a workaround

**Comment by texastoland** [comment]
Still not working? Title is my preferred sort but Release Date would be nice too 🙏🏼

**Comment by axiel7** [comment]
It seems AniList fixed it so I'll add it back

**Comment by axiel7** [comment]
AniList haven’t completely fixed the sort bug, so sorting by title and popularity shows the Mean Score instead of your score. 

I won’t remove title sorting again, let’s wait and hope that AniList fixes it someday

**Comment by texastoland** [comment]
I came to report the same thing. If it's a maximum number of pages (like 5) could you just sort client side?

**Comment by axiel7** [comment]
> If it's a maximum number of pages of results (5 for example) could you implement sorting client side?

I could do it but as you said it would only work fine with small lists so there's no point.

I recommend to use only those sorting options for browsing your list. If you wanna edit change the sort or open the details screen

**Comment by texastoland** [comment]
I CCed the maintainer (I think) on Discord maybe they can help 🤞🏼

**Comment by axiel7** [comment]
It seems AniList changed dev teams, let's hope they fix this API bug soon.

<img width="811" alt="Screenshot 2024-04-02 at 13 08 06" src="https://github.com/axiel7/AniHyou-android/assets/12379835/7c38e9d8-bbd9-49ef-86db-d664ce94831a">

**Comment by akyraisconfused** [comment]
sorting by title works fine on other clients so i was wondering if the api just dislikes your implementation or something (not that i understand this stuff)

**Comment by axiel7** [comment]
> sorting by title works fine on other clients

Probably they're doing some workaround. Could you give me an example?

**Comment by akyraisconfused** [comment]
im trying out a bunch of clients so of course! [AL-chan](https://github.com/zend10/AL-chan), [Aluminium](https://github.com/Emplexx/Aluminium), Anichive, [AniLib](https://github.com/rev0lgenX/AniLib), [Kurumi](https://github.com/subrotokumar/kurumi) and [Otraku](https://github.com/lotusprey/otraku) all have working alphabetical sorting.

**Comment by texastoland** [comment]
I thought it was a temporary problem but switching category (like planning vs watching) is currently broken (wrong grouping) too.

**Comment by akyraisconfused** [comment]
yeah, it sorts by title or popularity just fine but loads the wrong list

**Comment by axiel7** [comment]
It seems most of those clients are sorting the list locally instead of sending the sort param to the AniList API.

Personally I prefer to send the sort param to the API because:
1. It's simpler
2. It leverages the processing work for sorting the list to the servers instead of your device

For now I'll wait a bit more for AniList to fix this bug since they changed the dev team recently. But if they don't fix it in the next site update, I'll think about doing some workaround like that

**Comment by akyraisconfused** [comment]
yeah, i'd guessed it had something to do with client-side vs server-side. keep up the good work ^-^

**Comment by axiel7** [comment]
Finally fixed this in 1.3.3
