### ISSUE TITLE
Smiley score system Smiley's emotion does not match anilist.

### ISSUE THREAD

**Issue by Aiz0** [axiel7/AniHyou-android#38]
Anilist smileys. Ordered from happy to unhappy.
![ResizedImage_2023-11-01_05-06-54_1001](https://github.com/axiel7/AniHyou-android/assets/66974576/099fe52a-12e7-4139-b007-035edbe14f54)

Anihyou smileys. Reverse order. 
![ResizedImage_2023-11-01_05-05-33_7956](https://github.com/axiel7/AniHyou-android/assets/66974576/e0561d47-2c09-4f82-90ed-a16c23cb19d3)

I don't particulary care about the ordering but the middle smiley does not convey same emotion as the middle anilist smiley. It looks like the happy anilist smiley. This causes confusion.

**Comment by axiel7** [comment]
I wasn't able to find an icon for the 😐 that matches material design so I opted for that instead.

**Comment by Aiz0** [comment]
What about this one? [Sentiment neutral](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Asentiment_neutral%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024)

**Comment by axiel7** [comment]
> What about this one? [Sentiment neutral](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Asentiment_neutral%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024)

Oh that's perfect, idk why I didn't found it

**Comment by axiel7** [comment]
Fixed [1.2.1](https://github.com/axiel7/AniHyou-android/releases/tag/1.2.1)
