### ISSUE TITLE
Add a Message Seaction

### ISSUE THREAD

**Issue by kkisvitengah** [axiel7/AniHyou-android#4]
Just add a message section

**Comment by axiel7** [comment]
If do you mean notifications, then it's already implemented in the latest [beta](https://github.com/axiel7/AniHyou-android/releases/tag/1.1.0-beta03)

**Comment by kkisvitengah** [comment]
Oooh Sorry I didn't know about that 
When you are to release this update on Play Store ?

**Comment by axiel7** [comment]
> Oooh Sorry I didn't know about that When you are to release this update on Play Store ?

You can join the beta in Play Store, look for this option:
![Screenshot_20230620-122653](https://github.com/axiel7/AniHyou-android/assets/12379835/5ae7995e-4856-4e15-9f9a-7e5276f18bdc)

**Comment by kkisvitengah** [comment]
Thank You
I am wanting for message send update
Your applications ui looks so minimal to me I like that
