### ISSUE TITLE
Add Support for Custom Lists

### ISSUE THREAD

**Issue by Spacellary** [axiel7/AniHyou-android#40]
**Request (required)**

Support for at least adding and removing entries to and from **custom lists** (the Anilist feature).

**Additional context**

This was a teased as a possible feature in the future so I'm opening an issue to keep track of this feature and for possible discussion (feedback).

**Examples**

Users wouldn't be limited to just the default lists (Watching, Planning...) but to also assign entries to custom lists they created – Eg.: "Watching (Seasonal)", "90s Anime", "XYZ Studio Classics", "Special Favorites".

The creation of said lists doesn't have to be in the app, just adding and removing from them is enough functionality as creating and deleting them can already be done in the website, but of course that'd be cool for a future improvement.

<hr>

Thanks for the amazing work so far, Axiel!

**Comment by axiel7** [comment]
I can easily implement adding/removing to custom lists, it'll probably be in the next 1.2 version.

But for viewing the custom lists I'd need to do some breaking changes and it'll take some time.

**Comment by Spacellary** [comment]
@axiel7

Thanks for the insight and quick reply.

No rush, just wanted to make an issue so people can also track it. You bring a good point and it's definitely necessary to be able to see the custom lists in the app like we can with the default ones, so that's important for sure, will be looking forward to it of course.

**Comment by axiel7** [comment]
Added support for adding/removing only in (1.2.1)[https://github.com/axiel7/AniHyou-android/releases/tag/1.2.1]

**Comment by axiel7** [comment]
Now the only thing missing is the creating of new lists in-app, but I'll close this issue

**Comment by Spacellary** [comment]
@axiel7 Thanks for the hard work on these features so far! Cheers mate!
