### ISSUE TITLE
Can't increment empty field

### ISSUE THREAD

**Issue by Aiz0** [axiel7/AniHyou-android#47]
## Describe the bug

When adding a new media to your list all fields are empty.
When the fields are empty you can't use the increment buttons to add a value.
## To Reproduce
1. Go to any edit any media not on your list
2. Make sure the fields with +1 and -1 buttons are empty
3. Click the +1 button for any of those fields
4. See that the field remains empty.

## Expected behavior

I expect the field to hold a 1 after incrementing because the assumed default value is 0. This would be consistent with the Anilist website.

## Screenshots
![ResizedImage_2023-11-10_22-24-00_1242](https://github.com/axiel7/AniHyou-android/assets/66974576/e0a8b416-1732-4d06-aa28-c4699a08f503)
All fields with increment buttons shown here are empty and can't be incremted.

**Enviroment (required)**
 - Device model: SM-G960F
 - Android version: 10
 - App version: 1.2.1

**Comment by axiel7** [comment]
[Fixed](https://github.com/axiel7/AniHyou-android/commit/ca54995767abe31f3511a685769b647c0c22b30e)

**Comment by Aiz0** [comment]
Don't forget to also fix repeat count
https://github.com/axiel7/AniHyou-android/blob/63930914e4214b9b176dfae5cbdd6888aa024c84/app/src/main/java/com/axiel7/anihyou/ui/screens/mediadetails/edit/EditMediaSheet.kt#L323
