### ISSUE TITLE
After adding a new media the "Add" button doesn't update.

### ISSUE THREAD

**Issue by Aiz0** [axiel7/AniHyou-android#48]
## Describe the bug
After adding a new media the "Add" button doesn't update to show the status.
See screenshot

## To Reproduce
1. Go to any media not on your list.
2. Add it to your list.
4. See that the "Add" button is still displayed.

## Expected behavior
Just like when changing the status of a media already on your list, I expect the button to update.

## Screenshots
![ResizedImage_2023-11-10_22-53-08_2213](https://github.com/axiel7/AniHyou-android/assets/66974576/a75736a1-e23d-4236-abca-e3e45677d27e)

The button after adding a manga to planning.

## Enviroment
 - Device model: SM-G960F
 - Android version: 10
 - App version: 1.2.1

**Comment by axiel7** [comment]
Thanks for reporting! I just [fixed](https://github.com/axiel7/AniHyou-android/commit/63930914e4214b9b176dfae5cbdd6888aa024c84) it and I'll upload a new beta in the next days
