### ISSUE TITLE
Allow long click to edit media in more places.

### ISSUE THREAD

**Issue by Aiz0** [axiel7/AniHyou-android#49]
## Request
When browsing your Anime and Manga lists you can long click an entry to bring up the edit sheet.
It would be useful if this was possible in more places.

Some examples where I think it should be possible to do so:
- Lists in discover tab.
- Lists in explore tab.
- Staff/Character/Studio Media list.
- Activity feed (least important imo).

This would make it easier to quickly add/edit media for example when planning anime to watch next season.

## Additional context
Bringing up the edit sheet with long click does work when on a search page, but only for media already on your list.
I hope that long click for edit sheet could also be added for media not on your list.

Additionally, for the lists above I would like to be able to see if a media is on my list similar to how it looks on the search page.

**Comment by axiel7** [comment]
Sure, I already have plans to implement it. I started from the search list but it'll be added in more places

**Comment by axiel7** [comment]
I uploaded a new beta build on discord with this. I'll upload it to play store beta later
