### ISSUE TITLE
Make search bar like in MoeList

### ISSUE THREAD

**Issue by HotarunIchijou** [axiel7/AniHyou-android#5]
**Request**
I think that there's too much elements in navbar so it probably would be better if you gonna make a search bar like you did in your other project called MoeList

**Example**
![](https://github.com/axiel7/AniHyou-android/assets/113282550/d0e8168e-6219-4205-ad04-883f9484ecc3)

**Comment by axiel7** [comment]
I don’t think there are too many elements (a lot of apps have 5 like twitter or instagram for example).

Also it wouldn’t be space to put the Anime/Manga charts buttons
