### ISSUE TITLE
Can't do search with empty string in explore tab

### ISSUE THREAD

**Issue by Aiz0** [axiel7/AniHyou-android#50]
## Describe the bug
It's not possible to do a search with an empty string after already searching for something.

Sometimes I'm able to get it back by fiddling with the filter, sort, and category buttons.
This is not consistent though.

## To Reproduce
1. Go to the explore tab
2. Click on search bar
3. Type in anything to search for (I used "a") and then press enter to search.
4. Clear the field and press enter to try to search again.
5. No search will be performed and you can't get empty search string results back.

## Expected behavior
Pressing enter with an empty search string should perform a search.

## Enviroment
 - Device model: SM-G960F
 - Android version: 10
 - App version: 1.2.1

**Comment by axiel7** [comment]
Thanks for reporting. I put the empty check back when there weren't any filters but now it makes sense

**Comment by axiel7** [comment]
[Fixed](https://github.com/axiel7/AniHyou-android/commit/99d77444db6e96da3327f0f1c2b03490201cd883)
