### ISSUE TITLE
Autofill empty start date when media set to completed

### ISSUE THREAD

**Issue by Aiz0** [axiel7/AniHyou-android#52]
## Request
When setting media as completed the end date gets auto-filled with the current date.
I would also like the start date to be auto-filled if it's empty.

## Additional context
This is useful when adding a new media that you finished in the same day.
Movies, oneshot manga and such.

There might be cases where the user doesn't know the start date, So I don't think it should be auto-filled when status is changed to completed from anything other than planning.

**Comment by axiel7** [comment]
I think this would be an undesired behavior for some users. The current behavior in AniHyou is the same as AniList site so I don't think a change is needed

**Comment by Aiz0** [comment]
I can understand that decision, I just can't see many situations where you would want the end date filled but not the start date when adding a new media to your list.

I guess bringing this up to AniList would be better.

**Comment by Aiz0** [comment]
Closing this as not planned.
