### ISSUE TITLE
Can't search again after hiding keyboard

### ISSUE THREAD

**Issue by Aiz0** [axiel7/AniHyou-android#56]
### Describe the bug

In the explore tab, After hiding the keyboard during a search you can't get it back by pressing the search bar again.
Screenshot might explain more.

### Steps to reproduce the behavior:
1. Go to the explore tab
2. Click on the search bar
3. Click on the back button to hide the keyboard.
4. Search bar is still showing the cursor there.
5. Try to click on the search field again to do another search.
6. See that the keyboard never comes back.

### Alternate steps.
3. Type in anything to search for and press enter.
4. Keyboard and cursor is still shown.
5. Hide Keyboard.
7. Try to click on search field.
8. See that the keyboard never comes back.

## Expected behavior
If the search bar is focused you should be able to press it again to show the keyboard again.

Additionally.
After pressing enter I expect focus should leave the search bar and the keyboard should be hidden.

## Screenshots

![ResizedImage_2023-11-30_23-43-22_1470](https://github.com/axiel7/AniHyou-android/assets/66974576/65caa3ab-cc9e-4644-9a5f-739b9375fa87)

## Enviroment
 - Device model: SM-G960F
 - Android version: 10
 - App version: 1.2.2

**Comment by axiel7** [comment]
This seems to be a bug with the default `SearchBar` component. I'll do some tests and open a bug report on Google issue tracker

**Comment by axiel7** [comment]
[Issue opened](https://issuetracker.google.com/issues/316036824)

**Comment by axiel7** [comment]
It has been [fixed](https://issuetracker.google.com/issues/311437241#comment8). Next version will have the fix
