### ISSUE TITLE
Screen previews are practically useless

### ISSUE THREAD

**Issue by GSculerlor** [axiel7/AniHyou-android#79]
**Describe the bug (required)**
I'm unsure if it falls into the bug report, but it makes more sense under bug rather than a feature request.
Currently, any screen/composable preview that requires a `ViewModel` instance is useless since it fails to render due to failed to instantiate the `ViewModel`. 

**Expected behavior**
The preview should be rendered on not only widget/composable functions without `ViewModel` but also screen/composable function that requires `ViewModel`

relevant docs: https://developer.android.com/jetpack/compose/tooling/previews#preview-viewmodel

**Comment by axiel7** [comment]
Yeah I plan to do some refactoring for that. I don't usually use the IDE previews so it wasn't my priority
