### ISSUE TITLE
[ENHANCEMENT] Make the UI and Texts compact.

### ISSUE THREAD

**Issue by zerobun** [axiel7/AniHyou-android#85]
**Request (required)**
Describe the feature you want to be implemented.

For me personally, it feels that the information within the app is taking too much space on the screen because they are quite big, having the option to make the ui and the texts within more compact would be nice, which will mean you can see more of the info within the same given space on the screen.

**Additional context (optinal)**
Add any other context or app screenshots about the feature request here.

**Examples (optional)**
Show here examples of the feature if exists in other app.

This is an example of how this bit of info is taking too much space within the screen (in my opinion) so making it all more compact without losing info would be nice. 
![Screenshot_20231231-095734](https://github.com/axiel7/AniHyou-android/assets/127630316/1c30a1f6-db12-463f-a8f0-10954e167031)

**Comment by axiel7** [comment]
I think this is related to your phone display dpi, isn't the same on other apps?

**Comment by zerobun** [comment]
> I think this is related to your phone display dpi, isn't the same on other apps?

Yes most likely, I'm fine with other apps look like, but this one jus feel off to me. That's why I have suggested that option to be able to make things more compact if it's possible.
