### ISSUE TITLE
Setting for default list status

### ISSUE THREAD

**Issue by nightkaamos** [axiel7/AniHyou-android#86]
Hi bro. I want some feature in Anime tab. If you switch to Anime List tab
![Screenshot_20240101-093241_AniHyou.jpg](https://github.com/axiel7/AniHyou-android/assets/155342349/ee21fa88-fd82-47c0-a16c-920f8108c63c)

you will see default "Watching" option all the time. I don't usually use it. I want to set it "Planning" forever. It's so irritating to switch every time. Can you give an option to change default option ?

**Comment by axiel7** [comment]
I think most people use Watching as default but yeah I can add a setting for that

**Comment by nightkaamos** [comment]
I am not urging you. Take your time and add this feature please. Thank you for responding.

**Comment by axiel7** [comment]
I think I'll do it so the last status you selected is the one opened by default. Similar to how the bottom tabs works
