### ISSUE TITLE
Related items in series view are directed to people instead of other anime / manga/ ln

### ISSUE THREAD

**Issue by jaroslaw-buszowiecki** [axiel7/AniHyou-android#88]
**Describe the bug (required)**
As the title states.

**To Reproduce**
1. Go to any series, for example 'Classroom of the Elite Season 3'
2. Click on 'related entries'
3. Pick any related series
4. Get redirected to a person instead of anime.

**Expected behavior**
Redirect to the item that was clicked.

**Screenshots**
![Screenshot_2024-01-04-12-04-44-11_65c98e98fed398536bf0a4b3f9f52667.jpg](https://github.com/axiel7/AniHyou-android/assets/64857350/19612ec2-da0c-4269-845c-7f1d4d2f03c6)

![Screenshot_2024-01-04-12-04-48-73_65c98e98fed398536bf0a4b3f9f52667.jpg](https://github.com/axiel7/AniHyou-android/assets/64857350/b63ecf6e-f54f-4cb7-858e-9e023f5dbe13)

https://github.com/axiel7/AniHyou-android/assets/64857350/c7df98ac-56a5-4234-8cba-8bf463e4fc5c

**Enviroment (required)**
 - Device model: RealMe GT Master Edition RMX3363
 - Android version: 13
 - App version: 1.2.4 (47)

**Additional context (optional)**

**Comment by axiel7** [comment]
If I'm not mistaken, this bug is only present in the 1.2.4 beta.

Either way I already fixed it, wait for a new version
