### ISSUE TITLE
Show next episode

### ISSUE THREAD

**Issue by maicol07** [axiel7/AniHyou-android#91]
**Request (required)**
A section in anime detail and something in the anime list (a button or a text (episode number and title)) to show the next episode to watch based on the latest episode watched.

**Additional context (optinal)**
None

**Examples (optional)**
None

**Comment by axiel7** [comment]
I don't quite understand you. The next episode to watch is the current episode progress plus one (?)

**Comment by maicol07** [comment]
> I don't quite understand you. The next episode to watch is the current episode progress (already showing) plus one (?).

Yes. Basically, it's only a matter of adding (in the anime list) the next episode title

**Comment by axiel7** [comment]
Oh so do you mean to show the episode title (eg: Episode 8 - Frieren the Slayer)?

If that's the case, there isn't enough space and I don't think it's an important data to show

**Comment by maicol07** [comment]
Yeah, I imagined it. However, it could be a new section in the anime detail screen. For example, when you click an anime in the anime list and you go to the anime detail screen, you can add the "Next episode" section before or after the episodes section that shows the next episode to watch

**Comment by axiel7** [comment]
>  we can add the "Next episode" section

Sure that sounds good! I can add a new section "Cotinue watching" and pick from the episodes list based on your progress
