### ISSUE TITLE
F-Droid reproducible build failed

### ISSUE THREAD

**Issue by linsui** [axiel7/AniHyou-android#96]
**Describe the bug (required)**
1.2.4 is not reproducible. Is the apk built from 9191aab5e2a58f27b3a5e0e4b3174580ac0756df?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Enviroment (required)**
 - Device model: 
 - Android version: 
 - App version: 

**Additional context (optional)**

**Comment by axiel7** [comment]
Mmm yeah the apk was compiled from that commit. I'll replace the files just in case.

Where can I see the pipeline log?

**Comment by axiel7** [comment]
I just [updated the fastlane changelog](https://github.com/axiel7/AniHyou-android/commit/7896a41aff95d6a2a75dcf7fd1a91fbc78879367) today because I forgot to do it before the 1.2.4 tag. So maybe it's compiling from that commit?

**Comment by linsui** [comment]
```
2024-01-18 07:31:44,769 DEBUG: > git checkout -f 9191aab5e2a58f27b3a5e0e4b3174580ac0756df
```

We build the apk from the tag. And your apk is also uploaded 3 days ago...

**Comment by axiel7** [comment]
So I don't understand then. I just compiled and reuploaded the apks built from [9191aab](https://github.com/axiel7/AniHyou-android/commit/9191aab5e2a58f27b3a5e0e4b3174580ac0756df). Could you re run the pipeline?

**Comment by linsui** [comment]
It's not reproducible... How do you build the apk?

**Comment by axiel7** [comment]
It seems [this](https://issuetracker.google.com/issues/266109851#comment4) may be related?

For reference, I'm building the apk on macOS (as always) with Android Studio 2023.1.1 Patch 1

**Comment by linsui** [comment]
I thought the new line issue is not related. The diff is very large so that I have no idea what happened. Maybe the jdk is different. We use openjdk 17. The AS may cause problem. And maybe you need to clean the cache.

**Comment by axiel7** [comment]
I'm using the jdk built-in AS with  version 17.0.7. I just cleaned cache, built and reuploaded the apks.

**Comment by axiel7** [comment]
So I just tried running `diffoscope` and these are the [results](https://try.diffoscope.org/hzrhvfqvaqbr.html). It's seems the  main differences are the META-INF files. Any idea what could be causing this?

**Comment by axiel7** [comment]
I just uploaded a new build and the [pipeline](https://gitlab.com/axiel7/fdroiddata/-/jobs/5965500691) passed.

What I did was updating to Java 11 and disable resource shrinking. I'm still don't know why the previous version was reproducible because it used Java 8 and resource shrinking...

**Comment by linsui** [comment]
Great! https://github.com/axiel7/AniHyou-android/commit/f40157ca13adf03b7b8abf80b041ee47301a6d47 This workground workd for some other apps too. I don't know how it works  though.

**Comment by axiel7** [comment]
@linsui sorry for the mention. But since the 1.2.4 tag didn't pass the pipeline, do I need to do something to trigger the 1.2.4-1 update? It has been more than 7 days since I created the [1.2.4-1](https://github.com/axiel7/AniHyou-android/tree/1.2.4-1) tag

**Comment by linsui** [comment]
It's a long cycle. :shrug: https://monitor.f-droid.org/builds/log/com.axiel7.anihyou/50#site-footer 1.2.4-1 has been built.

**Comment by licaon-kter** [comment]
can we reopen? https://gitlab.com/fdroid/fdroiddata/-/jobs/6453378854#L3236

difflog: 
[anyh53.log](https://github.com/axiel7/AniHyou-android/files/14722391/anyh53.log)

**Comment by axiel7** [comment]
Mmm I'm not sure what can be the issue now. Maybe the upgrade of AGP from 8.2.1 to 8.3.1? Also I'm using KSP now instead of KAPT

**Comment by axiel7** [comment]
I uploaded a new [1.2.5-1](https://github.com/axiel7/AniHyou-android/releases/tag/1.2.5-1) build [compiled](https://github.com/axiel7/AniHyou-android/actions/runs/8400964239) using GitHub Actions with ubuntu-latest and the [pipeline](https://gitlab.com/axiel7/fdroiddata/-/pipelines/1224861518) is now passing.

Maybe the issue was related with the recent Java bugs in the latest macOS 14.4, idk.

I opened a [MR](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14740) to re enable AniHyou.

**Comment by linsui** [comment]
It failed again https://monitor.f-droid.org/builds/log/com.axiel7.anihyou/75#site-footer but I can't reproduce it in the CI https://gitlab.com/linsui/fdroiddata/-/jobs/7228745450.

**Comment by axiel7** [comment]
Probably it has something to do with baseline profiles since I implemented it in the latest release. I'll investigate

**Comment by linsui** [comment]
I can't reproduce the problem in buildserver. No idea. Let's see if it builds in the next cycle.

**Comment by licaon-kter** [comment]
reopen, you've tagged https://github.com/axiel7/AniHyou-android/releases/tag/1.3.4 from 466f4188337fd257884f6b7cf6eb61b3e48e6375 but the APK is built from 5a26616421974db5dbe4bd5159cdcb588c8a98bc ?

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/7468833911

**Comment by axiel7** [comment]
My fault, sorry. I forgot to include the changelog txt so I deleted and recreated the tag because I assumed that file wouldn't cause any diff. 

I compiled the apks from [466f418](https://github.com/axiel7/AniHyou-android/commit/466f4188337fd257884f6b7cf6eb61b3e48e6375) and reuploaded them to the [1.3.4](https://github.com/axiel7/AniHyou-android/releases/tag/1.3.4) release. I think that should be enough.

**Comment by linsui** [comment]
It won't cause diff if you disable the vcs info. See https://f-droid.org/en/docs/Reproducible_Builds/#vcs-info.

**Comment by licaon-kter** [comment]
thanks, https://gitlab.com/fdroid/fdroiddata/-/commit/e96c0e74cefb3911fc0936d18af6dbe7fe1d1760
