### ISSUE TITLE
Material You theming not working in OneUI

### ISSUE THREAD

**Issue by acszo** [axiel7/AniHyou-android#99]
**Describe the bug (required)**
Since the last update material you doesn't work on a Samsung device (not sure if it happens on phones from other manufacturers too), it stays on the default blue theme (like in your screenshots), even if i change themes it stays the same

**Enviroment (required)**
 - Device model: S23u
 - Android version: 14
 - App version: 1.2.4

**Additional context (optional)**
The bug is caused by the material 3 compose library after the 1.2.0-beta02 update (rc01 has the same problem), with 1.2.0-beta01 works fine, just letting you know

**Comment by axiel7** [comment]
> rc01 has the same problem

Then I'll wait for a next rc or stable version. It works fine at least on my pixel phone.

**Comment by acszo** [comment]
sure, it also works fine on the emulator from android studio

**Comment by axiel7** [comment]
Can you reproduce this on 1.2.5?

**Comment by acszo** [comment]
Just tried, still not working. I found out more about it some time ago and it seems to only happen on Android 14 (older versions don't have this issue) on Samsung

**Comment by MNSEhub** [comment]
Still not fixed. Same issue
s22u,V14,OneUI 6.1.
Works in emulator...

**Comment by acszo** [comment]
It has been fixed with the newer version of OneUi (6.1.1)
